# Generated by Django 5.1.2 on 2024-10-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_employeetask_employee_alter_employeetask_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mock_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mock', models.CharField(max_length=200)),
            ],
        ),
    ]
