# Generated by Django 5.1.2 on 2024-10-20 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mock_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mock_Data',
        ),
    ]
